MOUSEKEY_ENABLE = no    # Mouse keys
RGBLIGHT_ENABLE = no    # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
TAP_DANCE_ENABLE = yes
RGB_MATRIX_ENABLE = yes
LTO_ENABLE = yes
WPM_ENABLE = yes
